### ISSUE TITLE
Game crashing when using Ice Bow Enchantment

### ISSUE THREAD

**Issue by Mad2k7** [Binaris00/Optional_enchants#3]
The game crashes when an arrow fired from a bow with the Ice Bow enchantment hits any mob. It happens with both modded and base game bows. It also happens even if it's the only enchantment on the bow. 

Not sure if broken due to mod conflicts or updates breaking things. I pasted the relevant crash report info below.

--------
fabric-api: Fabric API 0.96.11+1.20.4

Description: Ticking entity

java.lang.RuntimeException: Error loading the config for: ice_bow_effect_amplifier
	at binaris.optional_enchants.config.Config.getInt(Config.java:106)
	at binaris.optional_enchants.enchantment.Ice_Bow.method_8189(Ice_Bow.java:33)
	at net.minecraft.class_1890.method_8207(class_1890.java:179)
	at net.minecraft.class_1890.method_17883(class_1890.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1890.method_8220(class_1890.java:138)
	at net.minecraft.class_1890.method_8209(class_1890.java:144)
	at net.minecraft.class_1890.method_8213(class_1890.java:181)
	at net.minecraft.class_1665.method_7454(class_1665.java:403)
	at net.minecraft.class_1676.method_7488(class_1676.java:162)
	at net.minecraft.class_1665.method_5773(class_1665.java:235)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:761)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:363)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845)
	at net.minecraft.class_1132.method_3748(class_1132.java:110)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-----------

Thread: Server thread
Stacktrace:
	at binaris.optional_enchants.config.Config.getInt(Config.java:106)
	at binaris.optional_enchants.enchantment.Ice_Bow.method_8189(Ice_Bow.java:33)
	at net.minecraft.class_1890.method_8207(class_1890.java:179)
	at net.minecraft.class_1890.method_17883(class_1890.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1890.method_8220(class_1890.java:138)
	at net.minecraft.class_1890.method_8209(class_1890.java:144)
	at net.minecraft.class_1890.method_8213(class_1890.java:181)
	at net.minecraft.class_1665.method_7454(class_1665.java:403)
	at net.minecraft.class_1676.method_7488(class_1676.java:162)
	at net.minecraft.class_1665.method_5773(class_1665.java:235)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:761)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_3218.method_31420(class_3218.java:399)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
Mixins in Stacktrace:
	net.minecraft.class_1890:
		qu.quEnchantments.mixin.EnchantmentHelperMixin (qu-enchantments.mixins.json)
		reborncore.mixin.common.MixinEnchantmentHelper (reborncore.common.mixins.json)
		net.soulsweaponry.mixin.EnchantmentHelperMixin (soulsweapons.mixins.json)
		nourl.mythicmetals.mixin.EnchantmentHelperMixin (mythicmetals.mixins.json)
		net.lukas.crossbow_expansion.mixin.EnchantmentHelperMixin (crossbow_expansion.mixins.json)
		com.ilmusu.musuen.mixins.mixin.DemonicEnchantingTableLogicMixin$FixEnchantmentGenerationList (musuen.mixins.json)
		com.seacroak.basicweapons.mixin.EnchantmentHelperMixin (basicweapons.mixins.json)
		com.ilmusu.musuen.mixins.mixin.EnchantmentWithExtensions$EnchantmentHelperModifications (musuen.mixins.json)
		com.glisco.conjuring.mixin.EnchantmentHelperMixin (conjuring.mixins.json)
		me.pajic.enchantmentdisabler.mixin.EnchantmentHelperMixin (enchantmentdisabler.mixins.json)
		io.github.fourmisain.axesareweapons.common.mixin.EnchantmentHelperMixin (axesareweapons.common.mixins.json)
		net.darkhax.msmlegacy.mixin.MixinEnchantmentHelper (msmlegacy.mixins.json)
	net.minecraft.class_1665:
		virtuoel.pehkui.mixin.PersistentProjectileEntityMixin (pehkui.mixins.json)
		com.ilmusu.musuen.mixins.mixin.CustomCallbacksMixins$PersistentProjectileEntityCallbacks (musuen.mixins.json)
		net.soulsweaponry.mixin.PersistentProjectileMixin (soulsweapons.mixins.json)
		fuzs.puzzleslib.fabric.mixin.AbstractArrowFabricMixin (puzzleslib.fabric.mixins.json)
		binaris.optional_enchants.mixin.PersistentProjectileEntityMixin (optional_enchants.mixins.json)
		virtuoel.pehkui.mixin.compat1203plus.PersistentProjectileEntityMixin (pehkui.mixins.json)
		com.ilmusu.musuen.mixins.mixin.AccessorPersistentProjectileEntity (musuen.mixins.json)
		virtuoel.pehkui.mixin.compat116plus.PersistentProjectileEntityMixin (pehkui.mixins.json)
		qu.quEnchantments.mixin.PersistentProjectileEntityMixin (qu-enchantments.mixins.json)
	net.minecraft.class_1676:
		qu.quEnchantments.mixin.ProjectileEntityMixin (qu-enchantments.mixins.json)
		virtuoel.pehkui.mixin.compat116plus.ProjectileEntityMixin (pehkui.mixins.json)
		com.ilmusu.musuen.mixins.mixin.CustomCallbacksMixins$ProjectileEntityCallback (musuen.mixins.json)
		io.github.fourmisain.perfectaccuracy.mixin.ProjectileEntityMixin (perfectaccuracy.mixins.json)
	net.minecraft.class_3218:
		dev.architectury.mixin.fabric.MixinServerLevel (architectury.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.chunk_deadlock.ServerLevelMixin (modernfix-common.mixins.json)
		net.fabricmc.fabric.mixin.lookup.ServerWorldMixin (fabric-api-lookup-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.attachment.ServerWorldMixin (fabric-data-attachment-api-v1.mixins.json)
		net.darkhax.bedbenefits.mixin.MixinServerLevel (bedbenefits.fabric.mixins.json)
		com.blamejared.crafttweaker.mixin.common.transform.world.level.MixinServerLevel (crafttweaker.mixins.json)
		fuzs.puzzleslib.fabric.mixin.ServerLevelFabricMixin (puzzleslib.fabric.mixins.json)
		com.supermartijn642.additionallanterns.mixin.ServerLevelMixin (additionallanterns.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.cache_strongholds.ServerLevelMixin (modernfix-common.mixins.json)
		com.supermartijn642.movingelevators.mixin.ServerLevelMixin (movingelevators.mixins.json)
		com.unixkitty.timecontrol.mixin.ServerLevelMixin (timecontrol.mixins.json)
		com.terraformersmc.biolith.impl.mixin.MixinServerWorld (biolith.mixins.json)
		dev.onyxstudios.cca.mixin.chunk.common.MixinServerWorld (mixins.cardinal_components_chunk.json)
		fuzs.leavesbegone.mixin.ServerLevelMixin (leavesbegone.common.mixins.json)
		fr.rakambda.fallingtree.fabric.mixin.LevelMixin (fallingtree.mixins.json)
		glitchcore.mixin.MixinServerLevel (glitchcore.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.ServerWorldMixin (fabric-lifecycle-events-v1.mixins.json)
		fabric.net.mca.mixin.MixinServerWorld (fabric-mca.mixin.json)
		com.natamus.collective.fabric.mixin.ServerLevelMixin (collective_fabric.mixins.json)
		dev.onyxstudios.cca.mixin.entity.common.MixinServerWorld (mixins.cardinal_components_entity.json)
		dev.onyxstudios.cca.mixin.world.common.MixinServerWorld (mixins.cardinal_components_world.json)
		net.trique.mythicupgrades.mixin.ServerWorldMixin (mythicupgrades.mixins.json)
	net.minecraft.class_1937:
		dev.onyxstudios.cca.mixin.world.common.MixinWorld (mixins.cardinal_components_world.json)
		net.blay09.mods.balm.mixin.LevelMixin (balm.fabric.mixins.json)
		dev.architectury.mixin.fabric.MixinLevel (architectury.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.WorldMixin (lambdynlights.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.WorldMixin (fabric-lifecycle-events-v1.mixins.json)
		com.supermartijn642.movingelevators.mixin.LevelMixin (movingelevators.mixins.json)
		com.supermartijn642.additionallanterns.mixin.LevelMixin (additionallanterns.mixins.json)
		net.fabricmc.fabric.mixin.attachment.AttachmentTargetsMixin (fabric-data-attachment-api-v1.mixins.json)
		fuzs.puzzleslib.fabric.mixin.LevelFabricMixin (puzzleslib.fabric.mixins.json)

**Comment by Binaris00** [comment]
Fixed, wait until I release the new version ^^
thanks for helping this mod
